### PR TITLE
Modify/level2

### PR DESCRIPTION
**Pull request by Cookiezznz**
Modified level 1 & 2. All platforms pertain to map boundaries

### CODE REVIEW

**Comment by TomasMorton** [comment]
When I try to play it at https://ludum-dare-49.s3.ap-southeast-2.amazonaws.com/modify/level2/index.html, the player doesn't move properly, is that just on my end?

**Comment by Cookiezznz** [comment]
Sorry i have noclip on. Its at the bottom of the map js

**Review by baconeta — CHANGES_REQUESTED** [review]
looks good except don't push with noclip = true

**Comment by Cookiezznz** [comment]
> looks good except don't push with noclip = true

I did a josh

**Pull request closed without merging**
